services:
  proxy:
    volumes:
      - ${MARBLE_API_COMPONENT_DIR}/service-config.json:/static/services/marble-api.json:ro
      - ${MARBLE_API_COMPONENT_DIR}/config/proxy/conf.extra-service.d:/etc/nginx/conf.extra-service.d/marble-api:ro
